#
#  Copyright 2023 Paul Guyot <pguyot@kallisys.net>
#
#  SPDX-License-Identifier: Apache-2.0 OR LGPL-2.1-or-later
#

name: "Build and publish Elixir Sudoku site"

on: ["push"]

jobs:
  build:
    runs-on: ubuntu-latest
    container: elixir:1.17.3-otp-26
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install dependencies
        run: |
          mix deps.get
      - name: Test
        run: |
          mix test
      - name: Build WASM
        run: |
          mix popcorn.cook
      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: site
          path: static
          retention-days: 1
  publish:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download Artifact
        uses: actions/download-artifact@v3
        with:
          name: site
          path: static
      - name: Deploy to netlify
        run: |
          docker container run \
           -e NETLIFY_AUTH_TOKEN=$NETLIFY_AUTH_TOKEN \
           -e NETLIFY_SITE_ID=$NETLIFY_SITE_ID \
           -v ${PWD}:/project \
           ghcr.io/williamjacksn/netlify-cli \
           deploy --dir=static --prod
        env:
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}