#
#  Copyright 2025 Paul Guyot <pguyot@kallisys.net>
#
#  SPDX-License-Identifier: Apache-2.0 OR LGPL-2.1-or-later
#

name: "Build and publish Elixir Sudoku site"

on: ["push"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - uses: erlef/setup-beam@v1
        with:
          otp-version: 26.0.2
          elixir-version: 1.17.3
          hexpm-mirrors: |
            https://builds.hex.pm
            https://repo.hex.pm
            https://cdn.jsdelivr.net/hex
      - name: Install dependencies
        run: |
          mix deps.get
      - name: Test
        run: |
          mix test
      - name: Build WASM
        run: |
          mix popcorn.cook
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: site
          path: static
          retention-days: 1
  publish:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download Artifact
        uses: actions/download-artifact@v4
        with:
          name: site
          path: static
      - name: Deploy to netlify
        run: |
          mkdir .netlify
          chmod ugo+rw .netlify
          docker container run \
           -e NETLIFY_AUTH_TOKEN=$NETLIFY_AUTH_TOKEN \
           -e NETLIFY_SITE_ID=$NETLIFY_SITE_ID \
           -v ${PWD}:/project \
           ghcr.io/williamjacksn/netlify-cli \
           deploy --dir=static --prod
        env:
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
